name: finstagram
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.3.5
  firebase_core: ^3.11.0
  firebase_auth: ^5.4.2
  firebase_analytics: ^11.4.2
  cloud_firestore: ^5.6.3
  firebase_storage: ^12.4.2
  get_it: ^8.0.3
  flutter_spinkit: ^5.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
